apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website-ingress
spec:
  rules:
  - host: website1.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: website1-website-service
            port:
              number: 80
