apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: website1-
commonLabels:
  website: website1

resources:
- ../../base

patchesStrategicMerge:
- configmap.yaml
- ingress.yaml
