apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: website3-
commonLabels:
  website: website3

resources:
- ../../base

patchesStrategicMerge:
- configmap.yaml
- ingress.yaml
