apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: website2-
commonLabels:
  website: website2

resources:
- ../../base

patchesStrategicMerge:
- configmap.yaml
- ingress.yaml
